[base]
name = 'Hass Panel'
web_port = 5124
debug = true
user_config_dir = "../data/user_configs"
hass_url = "http://10.0.0.70:8123"
upload_dir = '../data/upload'

[update_cfg]
github_repo = "mrtian2016/hass-panel"
app_dir = "../frontend/build"
version_file = "../frontend/build/version.json"
tmp_dir = "/tmp/hass-panel-update"
exclude_path = ["media", "env.js", "env.template.js"]

[log]
log_output_dir = "logs"

[database]
sqlite_path = "../data/hass_panel.db"

[security]
SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
schemes = ["bcrypt"]

