version: '3'

services:
  hass-panel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    volumes:
      - ../data:/config/hass-panel
    environment:
      - REACT_APP_HASS_URL=http://10.0.0.70:8123
    restart: unless-stopped 