version: '3'

services:
  hass-panel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "51230:5123"
      - "51240:5124"
      - "51250:5125"
    volumes:
      - ../data/:/config/hass-panel/
    environment:
      - REACT_APP_HASS_URL=http://10.0.0.70:8123
      - WEBDAV_USERNAME=admin
      - WEBDAV_PASSWORD=admin
    restart: unless-stopped 